//
// Generated file, do not edit! Created by opp_msgc 4.3 from ChannelExchange.msg.
//

#ifndef _CHANNELEXCHANGE_M_H_
#define _CHANNELEXCHANGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>ChannelExchange.msg</tt> by opp_msgc.
 * <pre>
 * message ChannelExchange  {
 * 	int id;
 *     int channel;
 * }
 * </pre>
 */
class ChannelExchange : public ::cMessage
{
  protected:
    int id_var;
    int channel_var;

  private:
    void copy(const ChannelExchange& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ChannelExchange&);

  public:
    ChannelExchange(const char *name=NULL, int kind=0);
    ChannelExchange(const ChannelExchange& other);
    virtual ~ChannelExchange();
    ChannelExchange& operator=(const ChannelExchange& other);
    virtual ChannelExchange *dup() const {return new ChannelExchange(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual int getChannel() const;
    virtual void setChannel(int channel);
};

inline void doPacking(cCommBuffer *b, ChannelExchange& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ChannelExchange& obj) {obj.parsimUnpack(b);}


#endif // _CHANNELEXCHANGE_M_H_
