//
// Generated file, do not edit! Created by opp_msgc 4.3 from PositionExchange.msg.
//

#ifndef _POSITIONEXCHANGE_M_H_
#define _POSITIONEXCHANGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "Position.h"
// }}



/**
 * Class generated from <tt>PositionExchange.msg</tt> by opp_msgc.
 * <pre>
 * message PositionExchange  {
 * 	int id;
 * 	Position position;
 * }
 * </pre>
 */
class PositionExchange : public ::cMessage
{
  protected:
    int id_var;
    Position position_var;

  private:
    void copy(const PositionExchange& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PositionExchange&);

  public:
    PositionExchange(const char *name=NULL, int kind=0);
    PositionExchange(const PositionExchange& other);
    virtual ~PositionExchange();
    PositionExchange& operator=(const PositionExchange& other);
    virtual PositionExchange *dup() const {return new PositionExchange(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual Position& getPosition();
    virtual const Position& getPosition() const {return const_cast<PositionExchange*>(this)->getPosition();}
    virtual void setPosition(const Position& position);
};

inline void doPacking(cCommBuffer *b, PositionExchange& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PositionExchange& obj) {obj.parsimUnpack(b);}


#endif // _POSITIONEXCHANGE_M_H_
