//
// Generated file, do not edit! Created by opp_msgc 4.3 from SINR.msg.
//

#ifndef _SINR_M_H_
#define _SINR_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>SINR.msg</tt> by opp_msgc.
 * <pre>
 * message SINR  {
 * 	int msId;
 * 	double SINR[];
 * }
 * </pre>
 */
class SINR : public ::cMessage
{
  protected:
    int msId_var;
    double *SINR_var; // array ptr
    unsigned int SINR_arraysize;

  private:
    void copy(const SINR& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SINR&);

  public:
    SINR(const char *name=NULL, int kind=0);
    SINR(const SINR& other);
    virtual ~SINR();
    SINR& operator=(const SINR& other);
    virtual SINR *dup() const {return new SINR(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getMsId() const;
    virtual void setMsId(int msId);
    virtual void setSINRArraySize(unsigned int size);
    virtual unsigned int getSINRArraySize() const;
    virtual double getSINR(unsigned int k) const;
    virtual void setSINR(unsigned int k, double SINR);
};

inline void doPacking(cCommBuffer *b, SINR& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, SINR& obj) {obj.parsimUnpack(b);}


#endif // _SINR_M_H_
