//
// Generated file, do not edit! Created by opp_msgc 4.3 from TransmitRequest.msg.
//

#ifndef _TRANSMITREQUEST_M_H_
#define _TRANSMITREQUEST_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>TransmitRequest.msg</tt> by opp_msgc.
 * <pre>
 * message TransmitRequest  {
 * 	int id;
 * 	int packetCount;   
 * }
 * </pre>
 */
class TransmitRequest : public ::cMessage
{
  protected:
    int id_var;
    int packetCount_var;

  private:
    void copy(const TransmitRequest& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TransmitRequest&);

  public:
    TransmitRequest(const char *name=NULL, int kind=0);
    TransmitRequest(const TransmitRequest& other);
    virtual ~TransmitRequest();
    TransmitRequest& operator=(const TransmitRequest& other);
    virtual TransmitRequest *dup() const {return new TransmitRequest(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual int getPacketCount() const;
    virtual void setPacketCount(int packetCount);
};

inline void doPacking(cCommBuffer *b, TransmitRequest& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, TransmitRequest& obj) {obj.parsimUnpack(b);}


#endif // _TRANSMITREQUEST_M_H_
